FROM openjdk:21
COPY target/spring-cloud-api-gateway-0.0.1-SNAPSHOT.jar spring-cloud-api-gateway-0.0.1-SNAPSHOT.jar
EXPOSE 9090
ENTRYPOINT ["java","-jar","/spring-cloud-api-gateway-0.0.1-SNAPSHOT.jar"]